language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t yocca/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true -v /app/node_modules -v .:/app yocca/docker-react npm run test
