language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t yocca/docker-react -f Dockerfile.dev -v /app/node_modules -v .:/app .

script:
  - docker run -e CI=true yocca/docker-react npm run test
